#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/apollo-service.log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

#-------------------------- Elasticsearch output ------------------------------

#setup.template.name: "filebeat"
#setup.template.pattern: "filebeat-*"
#output.elasticsearch:

  #hosts: ["192.168.245.128:9200"]
  #index: "filebeat-%{+yyyy.MM.dd}"

#----------------------------- Logstash output --------------------------------

output.logstash:
  hosts: ["192.168.174.128:5044"]
